# @format
# docker-compose.yml
version: '3.8'
services:
    sbx1:
        container_name: sbx1_o4mini
        SBX_ID: 1,
        image: nvidia/cuda:12.9-runtime-ubuntu24.04
        runtime: nvidia
        env_file:
            - ../.env
        environment:
        MODEL_NAME: o4-mini-2025-04-16
        CONDITION: ${CONDITION}
        volumes:
            - ../:/app
            - ../logs:/app/logs
            - ../backups:/app/backups
        working_dir: /app
        command: bash -lc "conda activate pilot && python main.py --model ${MODEL_NAME} --condition ${CONDITION}"

    sbx2:
        container_name: sbx2_claude4
        SBX_ID: 2,
        image: nvidia/cuda:12.9-runtime-ubuntu24.04
        runtime: nvidia
        env_file:
            - ../.env
        environment:
        MODEL_NAME: claude-sonnet-4-20250514
        CONDITION: ${CONDITION}
        volumes:
            - ../pilot-code:/app
            - ../logs:/app/logs
            - ../backups:/app/backups
        working_dir: /app
        command: bash -lc "conda activate pilot && python main.py --model ${MODEL_NAME} --condition ${CONDITION}"

    sbx3:
        container_name: sbx3_llama3
        SBX_ID: 3,
        image: nvidia/cuda:12.9-runtime-ubuntu24.04
        runtime: nvidia
        env_file:
            - ../.env
        environment:
        MODEL_NAME: Llama3.1-8B-Instruct
        CONDITION: ${CONDITION}
        volumes:
            - ../pilot-code:/app
            - ../logs:/app/logs
            - ../backups:/app/backups
        working_dir: /app
        command: bash -lc "conda activate pilot && python main.py --model ${MODEL_NAME} --condition ${CONDITION}"

    sbx4:
        container_name: sbx4_mistral7b
        SBX_ID: 4,
        image: nvidia/cuda:12.9-runtime-ubuntu24.04
        runtime: nvidia
        env_file:
            - ../.env
        environment:
        MODEL_NAME: Mistral-7B-Instruct-v0.3
        CONDITION: ${CONDITION}
        volumes:
            - ../pilot-code:/app
            - ../logs:/app/logs
            - ../backups:/app/backups
        working_dir: /app
        command: bash -lc "conda activate pilot && python main.py --model ${MODEL_NAME} --condition ${CONDITION}"

