# @format
# docker-compose.yml
# version: '3.8'
services:
    sbx1:
        container_name: sbx1_o4mini
        build:
            context: .
            args:
                - HF_TOKEN=${HF_TOKEN}
        runtime: nvidia
        env_file:
            - ./.env
        environment:
            MODEL_ID: gpt-4o-mini-2024-07-18
            SBX_ID: 1
            HF_HOME: ${HF_CACHE_PATH}/huggingface
        volumes:
            - '/mnt/c/Work/CoT:/app'
            - '/mnt/e/CoT_Result/logs:/logs'
            - '/mnt/e/CoT_Result/backups:/backups'
        working_dir: /app
        command: conda run -n pilot python main.py
    sbx2:
        container_name: sbx2_claude4
        build:
            context: .
            args:
                - HF_TOKEN=${HF_TOKEN}
        runtime: nvidia
        env_file:
            - ./.env
        environment:
            MODEL_ID: claude-sonnet-4-20250514
            SBX_ID: 2
            HF_HOME: ${HF_CACHE_PATH}/huggingface
        volumes:
            - '/mnt/c/Work/CoT:/app'
            - '/mnt/e/CoT_Result/logs:/logs'
            - '/mnt/e/CoT_Result/backups:/backups'
        working_dir: /app
        command: conda run -n pilot python main.py
    sbx3:
        container_name: sbx3_llama3
        build:
            context: .
            args:
                - HF_TOKEN=${HF_TOKEN}
        runtime: nvidia
        env_file:
            - ./.env
        environment:
            MODEL_ID: meta-llama/Llama-3.1-8B-Instruct
            SBX_ID: 3
            HF_HOME: ${HF_CACHE_PATH}/huggingface
        volumes:
            - '/mnt/c/Work/CoT:/app'
            - '/mnt/e/CoT_Result/logs:/logs'
            - '/mnt/e/CoT_Result/backups:/backups'
        working_dir: /app
        command: conda run -n pilot python main.py
    sbx4:
        container_name: sbx4_mistral7b
        build:
            context: .
            args:
                - HF_TOKEN=${HF_TOKEN}
        runtime: nvidia
        env_file:
            - ./.env
        environment:
            MODEL_ID: mistralai/Mistral-7B-Instruct-v0.3
            SBX_ID: 4
            HF_HOME: ${HF_CACHE_PATH}/huggingface
        volumes:
            - '/mnt/c/Work/CoT:/app'
            - '/mnt/e/CoT_Result/logs:/logs'
            - '/mnt/e/CoT_Result/backups:/backups'
        working_dir: /app
        command: conda run -n pilot python main.py
