# @format
# environment.yml
# Conda environment definition for the Reward Engineering Pilot experiment.

name: pilot
channels:
    # - pytorch
    # - nvidia
    - conda-forge
    # - defaults
dependencies:
    - python=3.10
    - pip
